language: python

python:
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  include:
    - python: 2.7
      env: DJANGO=1.10
    - python: 2.7
      env: DJANGO=1.11

    - python: 3.5
      env: DJANGO=master
    - python: 3.6
      env: DJANGO=master

  allow_failures:
    - env: DJANGO=master

install: pip install tox-travis
script: tox
