language: python
sudo: required
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  include:
    - python: 2.7
      env: DJANGO=1.10
    - python: 3.4
      env: DJANGO=1.10
    - python: 3.5
      env: DJANGO=1.10
    - python: 3.6
      env: DJANGO=1.10

    - python: 2.7
      env: DJANGO=1.11
    - python: 3.4
      env: DJANGO=1.11
    - python: 3.5
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=1.11

    - python: 3.4
      env: DJANGO=2.0

  allow_failures:
    - env: DJANGO=master

install: pip install tox-travis
script: tox
